require_relative 'wikitop/version.rb'
require_relative 'wikitop/parser.rb'
require_relative 'wikitop/wiki_link.rb'
require_relative 'wikitop/string.rb'
require_relative 'wikitop/document.rb'
require_relative 'wikitop/phrase.rb'
